# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Divisi',
            new_name='Bagian',
        ),
        migrations.RenameField(
            model_name='karyawan',
            old_name='divisi',
            new_name='bagian',
        ),
        migrations.RemoveField(
            model_name='karyawan',
            name='jabatan',
        ),
        migrations.RemoveField(
            model_name='karyawan',
            name='jenis_kelamin',
        ),
        migrations.RemoveField(
            model_name='karyawan',
            name='no_rekening',
        ),
        migrations.RemoveField(
            model_name='karyawan',
            name='no_telepon',
        ),
        migrations.RemoveField(
            model_name='karyawan',
            name='pemilik_rekening',
        ),
        migrations.AlterField(
            model_name='akun',
            name='jenis_akun',
            field=models.CharField(choices=[('user', 'Karyawan'), ('admin', 'Administrator')], max_length=20),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='jenis_karyawan',
            field=models.CharField(choices=[('editor', 'Editor'), ('full', 'Full')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Jabatan',
        ),
    ]
