# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0002_auto_20170209_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karyawan',
            name='bagian',
        ),
        migrations.DeleteModel(
            name='Bagian',
        ),
    ]
