# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('appetizer', 'Appetizer'), ('main_course', 'Main Course'), ('dessert', 'Dessert')], default='appetizer', max_length=20),
            preserve_default=False,
        ),
    ]
