# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(default='linked', max_length=50),
        ),
    ]
