# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cobaan',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
